// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBkiBR3hpUZotj9qCZfj-znkHI0lRgTkns',
//     appId: '1:482123688743:web:cbcb79fbbabf85edb4d702',
//     messagingSenderId: '482123688743',
//     projectId: 'coherent-fx-344515',
//     authDomain: 'coherent-fx-344515.firebaseapp.com',
//     databaseURL: 'https://coherent-fx-344515-default-rtdb.firebaseio.com',
//     storageBucket: 'coherent-fx-344515.appspot.com',
//     measurementId: 'G-WVEJ8N0VQN',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyC9t29X6F3Cfjvdu5PnXxWKL2tdWcGIZIA',
//     appId: '1:482123688743:android:14318a2c7e632142b4d702',
//     messagingSenderId: '482123688743',
//     projectId: 'coherent-fx-344515',
//     databaseURL: 'https://coherent-fx-344515-default-rtdb.firebaseio.com',
//     storageBucket: 'coherent-fx-344515.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDSNfmFx5oeJbJwoQErVWvI5VlMoLqKsiI',
//     appId: '1:482123688743:ios:2cbd8689bbe9b334b4d702',
//     messagingSenderId: '482123688743',
//     projectId: 'coherent-fx-344515',
//     databaseURL: 'https://coherent-fx-344515-default-rtdb.firebaseio.com',
//     storageBucket: 'coherent-fx-344515.appspot.com',
//     androidClientId: '482123688743-sk9nuucdb4vgvjtl4o76i3hqung4a41u.apps.googleusercontent.com',
//     iosClientId: '482123688743-ks1l6q00gj6rgbfv4ovucs3f94fgmpb3.apps.googleusercontent.com',
//     iosBundleId: 'vku.com.vkuniversal',
//   );
// }
