###signup
POST http://localhost:5055/v1/api/vkuniversal/signup
Content-Type: application/json

{
     "name": "he24",
     "password": "abcd",
     "email": "ab@gmail.com"
}
###
POST http://localhost:5055/v1/api/vkuniversal/login
Content-Type: application/json

{
     "email": "abcd@vku.udn.vn",
     "password": "abc"
}

###
POST http://localhost:5055/v1/api/vkuniversal/logout
Content-Type: application/json
x-client-id:1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjkwLCJlbWFpbCI6ImFnZ0B2a3UudWRuLnZuIiwiaWF0IjoxNzExODk0MTQyLCJleHAiOjE3MTE4OTQyNjJ9.JIY6v5J4FvtSaohakH-4RpP5uV5woqr2rq-t3-ZMRNk

### handlerToken

POST http://localhost:5055/v1/api/vkuniversal/handlerRefreshToken
Content-Type: application/json
x-client-id:1
x-rtoken-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWJjZEB2a3UudWRuLnZuIiwiaWF0IjoxNzEzMDA0Nzg5LCJleHAiOjE3MTMwOTExODl9.fxxk1XliS-MadwwGHm5-DeN2COZITYElcE4EpEUhGEc